name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: prod
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.TOKEN }}
          filename: metrics.svg
          base: header, repositories                  # шапка + блок репозиториев
          config_timezone: Asia/Jerusalem

          # ── Languages: most used ───────────────────────────────────────────────
          plugin_languages: yes
          plugin_languages_sections: most-used        # показывать раздел most-used
          plugin_languages_limit: 8
          plugin_languages_details: bytes-size, percentage
          # опционально: исключить разметку/генерируемый код
          # plugin_languages_ignored: html, css, scss

          # ── Featured / Pinned repositories ────────────────────────────────────
          plugin_repositories: yes
          # перечисли избранные (featured) через запятую: owner/name
          plugin_repositories_featured: Jormundgar/SmartLibrarian
          # показать закреплённые (pinned) репозитории из твоего профиля
          plugin_repositories_pinned: 1               # количество (например 2–6)
